---
- name: Configure networking
  hosts: "firewall"
  connection: local
  tags: add_ike_gateway
  
  tasks:
  - name: Set Variables
    changed_when: False
    include_vars: vars.yml

  vars:
    device:
      ip_address: "{{ inventory_hostname }}"
      username: "{{ ansible_ssh_user }}"
      password: "{{ ansible_ssh_pass }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Add AM4 IKE Gateway
      paloaltonetworks.panos.panos_ike_gateway:
       provider: '{{ device }}'
       state: 'present'
       name: 'AM4_IKE_Gateway'
       version: 'ikev2'
       interface: 'ethernet1/1'
       enable_passive_mode: false
       enable_liveness_check: true
       liveness_check_interval: '5'
       peer_ip_value: '149.11.201.123'
       pre_shared_key: '-AQ==zPJb3ngM1sGjXlfX2+Qk6rbdv1I=ucInIpBmFcnkQK7zF4VO1w=='
       ikev2_crypto_profile: 'VPN-IKE-Crypto-Profile'
       commit: true
